import { BrowserRouter, Routes, Route, Navigate } from 'react-router-dom'
import { lazy, Suspense, useEffect, useRef, useState } from 'react'
import Login from './pages/login/Login.tsx'
import Hub from './pages/hub/Hub.tsx'
import AppModule from '@/pages/app/AppModule.tsx'
import SchoolRoomModule from '@/flagships/school-room/SchoolRoomModule.tsx'
import SkolaStatistiky from '@/flagships/school-room/SkolaStatistiky.tsx'
import SkolaUpozorneni from '@/flagships/school-room/SkolaUpozorneni.tsx'
import FitnessRoomModule from '@/flagships/fitness-room/FitnessRoomModule.tsx'
import EconomyRoomModule from '@/flagships/economy-room/EconomyRoomModule.tsx'
import GrowthRoomModule from '@/flagships/growth-room/GrowthRoomModule.tsx'
import MusicRoomModule from '@/flagships/music-room/MusicRoomModule.tsx'
import WriterRoomModule from '@/flagships/writer-room/WriterRoomModule.tsx'
import GamesHubModule from '@/pages/games/GamesHubModule.tsx'
import BoardGameModule from '@/boardgame/BoardGameModule.tsx'
import ProfilModule from '@/pages/profil/ProfilModule.tsx'
import RewardModule from '@/pages/reward/RewardModule.tsx'
import SettingsModule from '@/pages/setting/SettingsModule.tsx'
import NapovedaSekce from '@/pages/setting/components/NapovedaSekce'
import ShopModule from '@/pages/shop/ShopModule.tsx'
import AdminModule from '@/pages/admin/AdminModule.tsx'
import SupportModule from '@/pages/support/SupportModule.tsx'
const SocialModule = lazy(() => import('@/social/SocialModule'))
const SurvivalModule = lazy(() => import('@/survival/SurvivalModule'))
